tests:
  csv_path: test_data/data.csv

path:
  path_to_images: data/train-jpg
  train_path: data/train_df.csv
  val_path: data/valid_df.csv
  test_path: data/test_df.csv

training:
  seed: 39
  image_size: 224
